DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS AUDIT_TRAIL_RECORD;

CREATE TABLE STUDENT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  EMAIL_ID VARCHAR(250) DEFAULT NULL
);
 CREATE TABLE ADDRESS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ADDRESS_LINE_1 VARCHAR(250) NOT NULL,
  ADDRESS_LINE_2 VARCHAR(250),
  CITY VARCHAR(250) NOT NULL,
  COUNTRY VARCHAR(250) NOT NULL,
  POSTAL_CODE VARCHAR(250) NOT NULL
);
CREATE TABLE AUDIT_TRAIL_RECORD (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  UPDATED_TIME DATE NOT NULL,
  UPDATED_BY VARCHAR(250) NOT NULL,
  ACTION_CODE VARCHAR(250) DEFAULT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL
);
commit;
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, EMAIL_ID) VALUES
  ('Shakti', 'S', 'Shakti@gmail.com');
INSERT INTO ADDRESS (ADDRESS_LINE_1,CITY ,COUNTRY,POSTAL_CODE) VALUES
  ('Shakti', 'AMS', 'NL', '1150');
INSERT INTO AUDIT_TRAIL_RECORD (UPDATED_TIME,UPDATED_BY ,ACTION_CODE,DESCRIPTION) VALUES
  (GetDate(), 'admin', 'CREATE', 'New Student details added');
  commit;